version: 2
jobs:
  test:
    docker:
      - image: circleci/node:10.0.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm test
  build-latest:
    docker:
      - image: circleci/node:10.0.0
    steps:
      - checkout
      - run:
          name: Install rsync
          command: sudo apt install -y rsync
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build CSS and JavaScript
          command: npm run build
      - run:
          name: Deploy theme
          command: bash build/deploy.sh
      - run:
          name: Purge Cloudflare cache
          command: bash build/purge_cache.sh
workflows:
  version: 2
  build-latest:
    jobs:
      - test
      - build-latest:
          requires:
            - test
          filters:
            branches:
              only:
                - master
