version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8.11.1
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm test
  build-latest:
    docker:
      - image: circleci/node:8.11.1
    steps:
      - checkout
      - run: sudo apt install -y rsync
      - run: npm install
      - run: npm run build
      - run: bash deploy.sh
workflows:
  version: 2
  build-latest:
    jobs:
      - test
      - build-latest:
          requires:
            - test
          filters:
            branches:
              only:
                - master
